// $aa = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '1'");
// $data1 = mysqli_fetch_array($aa);
// $ab = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '2'");
// $data2 = mysqli_fetch_array($aa);
// $ac = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '3'");
// $data3 = mysqli_fetch_array($aa);
// $ad = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '4'");
// $data4 = mysqli_fetch_array($aa);
// $ae = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '5'");
// $data5 = mysqli_fetch_array($aa);
// $af = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '6'");
// $data6 = mysqli_fetch_array($aa);
// $ag = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '7'");
// $data7 = mysqli_fetch_array($aa);
// $ah = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '8'");
// $data8 = mysqli_fetch_array($aa);
// $ai = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '9'");
// $data9 = mysqli_fetch_array($aa);
// $aj = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '10'");
// $data10 = mysqli_fetch_array($aa);
// $ak = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '11'");
// $data11 = mysqli_fetch_array($aa);
// $al = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '12'");
// $data12 = mysqli_fetch_array($aa);
// $am = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '13'");
// $data13 = mysqli_fetch_array($aa);
// $an = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '14'");
// $data14 = mysqli_fetch_array($aa);
// $ao = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '15'");
// $data15 = mysqli_fetch_array($aa);
// $ap = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '16'");
// $data16 = mysqli_fetch_array($aa);
// $aq = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '17'");
// $data17 = mysqli_fetch_array($aa);
// $ar = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '18'");
// $data18 = mysqli_fetch_array($aa);
// $as = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '19'");
// $data19 = mysqli_fetch_array($aa);
// $at = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '20'");
// $data20 = mysqli_fetch_array($aa);
// $au = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '21'");
// $data21 = mysqli_fetch_array($aa);
// $av = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '22'");
// $data22 = mysqli_fetch_array($aa);
// $aw = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '23'");
// $data23 = mysqli_fetch_array($aa);
// $ax = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '24'");
// $data24 = mysqli_fetch_array($aa);
// $ay = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '25'");
// $data25 = mysqli_fetch_array($aa);
// $az = mysqli_query($koneksi, "SELECT * FROM tbl_mapel where no_urut = '26'");
// $data26 = mysqli_fetch_array($aa);